<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  octalmage\WPUnitTestAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * WP Unit Test API.
 *
 * #### An API to collect unit test results.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace octalmage\WPUnitTestAPI;

use \octalmage\WPUnitTestAPI\Configuration;
use \octalmage\WPUnitTestAPI\ApiClient;
use \octalmage\WPUnitTestAPI\ApiException;
use \octalmage\WPUnitTestAPI\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  octalmage\WPUnitTestAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addResults
     *
     * .
     *
     */
    public function testAddResults()
    {

    }

}
